//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class ApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    next(): Promise<AiNextTurnDto> {
        let url_ = this.baseUrl + "/api/Ai/next";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processNext(_response);
        });
    }

    protected processNext(response: Response): Promise<AiNextTurnDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AiNextTurnDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AiNextTurnDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    act(body: AiActRequest | undefined): Promise<AiNextTurnDto> {
        let url_ = this.baseUrl + "/api/Ai/act";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAct(_response);
        });
    }

    protected processAct(response: Response): Promise<AiNextTurnDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AiNextTurnDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AiNextTurnDto>(null as any);
    }

    /**
     * @return OK
     */
    ensure(): Promise<void> {
        let url_ = this.baseUrl + "/api/Game/ensure";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processEnsure(_response);
        });
    }

    protected processEnsure(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    state(): Promise<void> {
        let url_ = this.baseUrl + "/api/Game/state";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processState(_response);
        });
    }

    protected processState(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    place(body: PlaceRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Game/place";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPlace(_response);
        });
    }

    protected processPlace(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    check(): Promise<void> {
        let url_ = this.baseUrl + "/api/Game/referee/check";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCheck(_response);
        });
    }

    protected processCheck(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    playersAll(): Promise<PlayerDto[]> {
        let url_ = this.baseUrl + "/api/Players";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPlayersAll(_response);
        });
    }

    protected processPlayersAll(response: Response): Promise<PlayerDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(PlayerDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PlayerDto[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    players(body: CreatePlayerRequest | undefined): Promise<PlayerDto> {
        let url_ = this.baseUrl + "/api/Players";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPlayers(_response);
        });
    }

    protected processPlayers(response: Response): Promise<PlayerDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = PlayerDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PlayerDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    score(id: number, body: number | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Players/{id}/score";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processScore(_response);
        });
    }

    protected processScore(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    snapshot(): Promise<WorldSnapshotDto> {
        let url_ = this.baseUrl + "/api/World/snapshot";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSnapshot(_response);
        });
    }

    protected processSnapshot(response: Response): Promise<WorldSnapshotDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = WorldSnapshotDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WorldSnapshotDto>(null as any);
    }

    /**
     * @return OK
     */
    rulesGET(): Promise<WorldRulesDto> {
        let url_ = this.baseUrl + "/api/World/rules";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRulesGET(_response);
        });
    }

    protected processRulesGET(response: Response): Promise<WorldRulesDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = WorldRulesDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WorldRulesDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    rulesPUT(body: WorldRulesDto | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/World/rules";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRulesPUT(_response);
        });
    }

    protected processRulesPUT(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    direction(): Promise<string> {
        let url_ = this.baseUrl + "/api/World/direction";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDirection(_response);
        });
    }

    protected processDirection(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @return OK
     */
    reset(): Promise<void> {
        let url_ = this.baseUrl + "/api/World/reset";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processReset(_response);
        });
    }

    protected processReset(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    view(): Promise<WorldViewDto> {
        let url_ = this.baseUrl + "/api/World/view";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processView(_response);
        });
    }

    protected processView(response: Response): Promise<WorldViewDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = WorldViewDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<WorldViewDto>(null as any);
    }
}

export class AiActRequest implements IAiActRequest {
    role?: string | undefined;
    action?: string | undefined;
    payload?: any | undefined;

    constructor(data?: IAiActRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.role = _data["role"];
            this.action = _data["action"];
            this.payload = _data["payload"];
        }
    }

    static fromJS(data: any): AiActRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AiActRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["role"] = this.role;
        data["action"] = this.action;
        data["payload"] = this.payload;
        return data;
    }
}

export interface IAiActRequest {
    role?: string | undefined;
    action?: string | undefined;
    payload?: any | undefined;
}

export class AiNextTurnDto implements IAiNextTurnDto {
    nextRole?: string | undefined;
    roleContext?: any | undefined;
    worldSnapshot?: WorldSnapshotDto;
    rules?: WorldRulesDto;
    direction?: string | undefined;
    delaySeconds?: number;
    lastPlaceClaimWin?: boolean | undefined;

    constructor(data?: IAiNextTurnDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.nextRole = _data["nextRole"];
            this.roleContext = _data["roleContext"];
            this.worldSnapshot = _data["worldSnapshot"] ? WorldSnapshotDto.fromJS(_data["worldSnapshot"]) : undefined as any;
            this.rules = _data["rules"] ? WorldRulesDto.fromJS(_data["rules"]) : undefined as any;
            this.direction = _data["direction"];
            this.delaySeconds = _data["delaySeconds"];
            this.lastPlaceClaimWin = _data["lastPlaceClaimWin"];
        }
    }

    static fromJS(data: any): AiNextTurnDto {
        data = typeof data === 'object' ? data : {};
        let result = new AiNextTurnDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["nextRole"] = this.nextRole;
        data["roleContext"] = this.roleContext;
        data["worldSnapshot"] = this.worldSnapshot ? this.worldSnapshot.toJSON() : undefined as any;
        data["rules"] = this.rules ? this.rules.toJSON() : undefined as any;
        data["direction"] = this.direction;
        data["delaySeconds"] = this.delaySeconds;
        data["lastPlaceClaimWin"] = this.lastPlaceClaimWin;
        return data;
    }
}

export interface IAiNextTurnDto {
    nextRole?: string | undefined;
    roleContext?: any | undefined;
    worldSnapshot?: WorldSnapshotDto;
    rules?: WorldRulesDto;
    direction?: string | undefined;
    delaySeconds?: number;
    lastPlaceClaimWin?: boolean | undefined;
}

export class CreatePlayerRequest implements ICreatePlayerRequest {
    color?: string | undefined;
    intelligence?: number;
    thought?: string | undefined;

    constructor(data?: ICreatePlayerRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.color = _data["color"];
            this.intelligence = _data["intelligence"];
            this.thought = _data["thought"];
        }
    }

    static fromJS(data: any): CreatePlayerRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreatePlayerRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["color"] = this.color;
        data["intelligence"] = this.intelligence;
        data["thought"] = this.thought;
        return data;
    }
}

export interface ICreatePlayerRequest {
    color?: string | undefined;
    intelligence?: number;
    thought?: string | undefined;
}

export class NarrativeEntryDto implements INarrativeEntryDto {
    role?: string | undefined;
    message?: string | undefined;
    at?: Date;

    constructor(data?: INarrativeEntryDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.role = _data["role"];
            this.message = _data["message"];
            this.at = _data["at"] ? new Date(_data["at"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): NarrativeEntryDto {
        data = typeof data === 'object' ? data : {};
        let result = new NarrativeEntryDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["role"] = this.role;
        data["message"] = this.message;
        data["at"] = this.at ? this.at.toISOString() : undefined as any;
        return data;
    }
}

export interface INarrativeEntryDto {
    role?: string | undefined;
    message?: string | undefined;
    at?: Date;
}

export class PlaceRequest implements IPlaceRequest {
    color?: string | undefined;
    x?: number;
    y?: number;

    constructor(data?: IPlaceRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.color = _data["color"];
            this.x = _data["x"];
            this.y = _data["y"];
        }
    }

    static fromJS(data: any): PlaceRequest {
        data = typeof data === 'object' ? data : {};
        let result = new PlaceRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["color"] = this.color;
        data["x"] = this.x;
        data["y"] = this.y;
        return data;
    }
}

export interface IPlaceRequest {
    color?: string | undefined;
    x?: number;
    y?: number;
}

export class PlayerDto implements IPlayerDto {
    id?: number;
    color?: string | undefined;
    intelligence?: number;
    score?: number;

    constructor(data?: IPlayerDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.color = _data["color"];
            this.intelligence = _data["intelligence"];
            this.score = _data["score"];
        }
    }

    static fromJS(data: any): PlayerDto {
        data = typeof data === 'object' ? data : {};
        let result = new PlayerDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["color"] = this.color;
        data["intelligence"] = this.intelligence;
        data["score"] = this.score;
        return data;
    }
}

export interface IPlayerDto {
    id?: number;
    color?: string | undefined;
    intelligence?: number;
    score?: number;
}

export class PlayerViewDto implements IPlayerViewDto {
    id?: number;
    color?: string | undefined;
    intelligence?: number;
    score?: number;
    createdAt?: Date;

    constructor(data?: IPlayerViewDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.color = _data["color"];
            this.intelligence = _data["intelligence"];
            this.score = _data["score"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): PlayerViewDto {
        data = typeof data === 'object' ? data : {};
        let result = new PlayerViewDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["color"] = this.color;
        data["intelligence"] = this.intelligence;
        data["score"] = this.score;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        return data;
    }
}

export interface IPlayerViewDto {
    id?: number;
    color?: string | undefined;
    intelligence?: number;
    score?: number;
    createdAt?: Date;
}

export class WorldRulesDto implements IWorldRulesDto {
    minMovesBeforeWin?: number;
    blackAdvantage?: number;
    direction?: string | undefined;

    constructor(data?: IWorldRulesDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.minMovesBeforeWin = _data["minMovesBeforeWin"];
            this.blackAdvantage = _data["blackAdvantage"];
            this.direction = _data["direction"];
        }
    }

    static fromJS(data: any): WorldRulesDto {
        data = typeof data === 'object' ? data : {};
        let result = new WorldRulesDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["minMovesBeforeWin"] = this.minMovesBeforeWin;
        data["blackAdvantage"] = this.blackAdvantage;
        data["direction"] = this.direction;
        return data;
    }
}

export interface IWorldRulesDto {
    minMovesBeforeWin?: number;
    blackAdvantage?: number;
    direction?: string | undefined;
}

export class WorldSnapshotDto implements IWorldSnapshotDto {
    boardSize?: number;
    board?: number[][] | undefined;
    currentTurn?: string | undefined;
    moveCount?: number;
    gameStatus?: string | undefined;
    blackPlayerId?: number | undefined;
    whitePlayerId?: number | undefined;
    winner?: string | undefined;
    lastMoveX?: number | undefined;
    lastMoveY?: number | undefined;

    constructor(data?: IWorldSnapshotDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.boardSize = _data["boardSize"];
            if (Array.isArray(_data["board"])) {
                this.board = [] as any;
                for (let item of _data["board"])
                    this.board!.push(item);
            }
            this.currentTurn = _data["currentTurn"];
            this.moveCount = _data["moveCount"];
            this.gameStatus = _data["gameStatus"];
            this.blackPlayerId = _data["blackPlayerId"];
            this.whitePlayerId = _data["whitePlayerId"];
            this.winner = _data["winner"];
            this.lastMoveX = _data["lastMoveX"];
            this.lastMoveY = _data["lastMoveY"];
        }
    }

    static fromJS(data: any): WorldSnapshotDto {
        data = typeof data === 'object' ? data : {};
        let result = new WorldSnapshotDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["boardSize"] = this.boardSize;
        if (Array.isArray(this.board)) {
            data["board"] = [];
            for (let item of this.board)
                data["board"].push(item);
        }
        data["currentTurn"] = this.currentTurn;
        data["moveCount"] = this.moveCount;
        data["gameStatus"] = this.gameStatus;
        data["blackPlayerId"] = this.blackPlayerId;
        data["whitePlayerId"] = this.whitePlayerId;
        data["winner"] = this.winner;
        data["lastMoveX"] = this.lastMoveX;
        data["lastMoveY"] = this.lastMoveY;
        return data;
    }
}

export interface IWorldSnapshotDto {
    boardSize?: number;
    board?: number[][] | undefined;
    currentTurn?: string | undefined;
    moveCount?: number;
    gameStatus?: string | undefined;
    blackPlayerId?: number | undefined;
    whitePlayerId?: number | undefined;
    winner?: string | undefined;
    lastMoveX?: number | undefined;
    lastMoveY?: number | undefined;
}

export class WorldViewDto implements IWorldViewDto {
    snapshot?: WorldSnapshotDto;
    rules?: WorldRulesDto;
    direction?: string | undefined;
    blackPlayer?: PlayerViewDto;
    whitePlayer?: PlayerViewDto;
    narrative?: NarrativeEntryDto[] | undefined;

    constructor(data?: IWorldViewDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.snapshot = _data["snapshot"] ? WorldSnapshotDto.fromJS(_data["snapshot"]) : undefined as any;
            this.rules = _data["rules"] ? WorldRulesDto.fromJS(_data["rules"]) : undefined as any;
            this.direction = _data["direction"];
            this.blackPlayer = _data["blackPlayer"] ? PlayerViewDto.fromJS(_data["blackPlayer"]) : undefined as any;
            this.whitePlayer = _data["whitePlayer"] ? PlayerViewDto.fromJS(_data["whitePlayer"]) : undefined as any;
            if (Array.isArray(_data["narrative"])) {
                this.narrative = [] as any;
                for (let item of _data["narrative"])
                    this.narrative!.push(NarrativeEntryDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): WorldViewDto {
        data = typeof data === 'object' ? data : {};
        let result = new WorldViewDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["snapshot"] = this.snapshot ? this.snapshot.toJSON() : undefined as any;
        data["rules"] = this.rules ? this.rules.toJSON() : undefined as any;
        data["direction"] = this.direction;
        data["blackPlayer"] = this.blackPlayer ? this.blackPlayer.toJSON() : undefined as any;
        data["whitePlayer"] = this.whitePlayer ? this.whitePlayer.toJSON() : undefined as any;
        if (Array.isArray(this.narrative)) {
            data["narrative"] = [];
            for (let item of this.narrative)
                data["narrative"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IWorldViewDto {
    snapshot?: WorldSnapshotDto;
    rules?: WorldRulesDto;
    direction?: string | undefined;
    blackPlayer?: PlayerViewDto;
    whitePlayer?: PlayerViewDto;
    narrative?: NarrativeEntryDto[] | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}